import Foundation

// MARK: - Key Encapsulation Mechanism (KEM) Wrapper

final class LibOQSKEM {
    private var kem: UnsafeMutablePointer<OQS_KEM>?
    private let algorithm: LibOQSKEMAlgorithm
    private let lock = NSLock()

    // MARK: - Initialization & Cleanup

    /// Initialize KEM with given algorithm
    /// - Parameter algorithm: KEM algorithm to use
    /// - Throws: LibOQSError if algorithm not supported or initialization failed
    init(algorithm: LibOQSKEMAlgorithm) throws {
        self.algorithm = algorithm

        // Check if algorithm is enabled
        guard OQS_KEM_alg_is_enabled(algorithm.cString) == 1 else {
            throw LibOQSError.algorithmNotSupported(algorithm.rawValue)
        }

        // Create KEM object
        guard let kemPtr = OQS_KEM_new(algorithm.cString) else {
            throw LibOQSError.algorithmNotSupported(algorithm.rawValue)
        }

        self.kem = kemPtr
    }

    deinit {
        if let kem = kem {
            OQS_KEM_free(kem)
            self.kem = nil
        }
    }

    // MARK: - Key Generation

    /// Generate KEM keypair
    /// - Returns: LibOQSKeypair with public and secret keys
    /// - Throws: LibOQSError on failure
    func generateKeypair() throws -> LibOQSKeypair {
        lock.lock()
        defer { lock.unlock() }

        guard let kem = kem else {
            throw LibOQSError.moduleDeallocated
        }

        let kemStruct = kem.pointee

        // Allocate buffers
        guard let publicKeyBuf = LibOQSMemory.SecureBuffer(
            size: Int(kemStruct.length_public_key),
            secure: false // Public keys don't need secure allocation
        ) else {
            throw LibOQSError.memoryAllocationFailed
        }

        guard let secretKeyBuf = LibOQSMemory.SecureBuffer(
            size: Int(kemStruct.length_secret_key),
            secure: true // Secret keys MUST use secure allocation
        ) else {
            throw LibOQSError.memoryAllocationFailed
        }

        // Generate keypair
        let status = OQS_KEM_keypair(
            kem,
            publicKeyBuf.bytes,
            secretKeyBuf.bytes
        )

        guard status == OQS_SUCCESS else {
            throw LibOQSError.operationFailed("Keypair generation failed")
        }

        return LibOQSKeypair(
            publicKey: publicKeyBuf.toData(),
            secretKey: secretKeyBuf.toData()
        )
    }

    // MARK: - Encapsulation

    /// Encapsulate to generate shared secret and ciphertext
    /// Called by encapsulator to derive a shared secret that decapsulator can recover
    /// - Parameter publicKey: Public key from recipient (generated by generateKeypair)
    /// - Returns: Encapsulation containing ciphertext and shared secret
    /// - Throws: LibOQSError on failure
    func encapsulate(publicKey: Data) throws -> LibOQSEncapsulation {
        lock.lock()
        defer { lock.unlock() }

        guard let kem = kem else {
            throw LibOQSError.moduleDeallocated
        }

        let kemStruct = kem.pointee

        // Validate public key length
        guard publicKey.count == Int(kemStruct.length_public_key) else {
            throw LibOQSError.invalidKeyLength
        }

        // Allocate output buffers
        guard let ciphertextBuf = LibOQSMemory.SecureBuffer(
            size: Int(kemStruct.length_ciphertext),
            secure: false
        ) else {
            throw LibOQSError.memoryAllocationFailed
        }

        guard let sharedSecretBuf = LibOQSMemory.SecureBuffer(
            size: Int(kemStruct.length_shared_secret),
            secure: true // Shared secret is sensitive
        ) else {
            throw LibOQSError.memoryAllocationFailed
        }

        // Perform encapsulation
        let status = publicKey.withUnsafeBytes { pubKeyPtr in
            OQS_KEM_encaps(
                kem,
                ciphertextBuf.bytes,
                sharedSecretBuf.bytes,
                pubKeyPtr.baseAddress!.assumingMemoryBound(to: UInt8.self)
            )
        }

        guard status == OQS_SUCCESS else {
            throw LibOQSError.operationFailed("Encapsulation failed")
        }

        return LibOQSEncapsulation(
            ciphertext: ciphertextBuf.toData(),
            sharedSecret: sharedSecretBuf.toData()
        )
    }

    // MARK: - Decapsulation

    /// Decapsulate to recover shared secret
    /// Called by decapsulator with ciphertext from encapsulator to recover the same shared secret
    /// - Parameters:
    ///   - ciphertext: Ciphertext from encapsulator
    ///   - secretKey: Secret key from recipient (generated by generateKeypair)
    /// - Returns: Shared secret (should match encapsulator's shared secret)
    /// - Throws: LibOQSError on failure
    func decapsulate(ciphertext: Data, secretKey: Data) throws -> Data {
        lock.lock()
        defer { lock.unlock() }

        guard let kem = kem else {
            throw LibOQSError.moduleDeallocated
        }

        let kemStruct = kem.pointee

        // Validate buffer lengths
        guard ciphertext.count == Int(kemStruct.length_ciphertext) else {
            throw LibOQSError.invalidKeyLength
        }

        guard secretKey.count == Int(kemStruct.length_secret_key) else {
            throw LibOQSError.invalidKeyLength
        }

        // Allocate output buffer
        guard let sharedSecretBuf = LibOQSMemory.SecureBuffer(
            size: Int(kemStruct.length_shared_secret),
            secure: true // Shared secret is sensitive
        ) else {
            throw LibOQSError.memoryAllocationFailed
        }

        // Perform decapsulation
        let status = ciphertext.withUnsafeBytes { ctPtr in
            secretKey.withUnsafeBytes { skPtr in
                OQS_KEM_decaps(
                    kem,
                    sharedSecretBuf.bytes,
                    ctPtr.baseAddress!.assumingMemoryBound(to: UInt8.self),
                    skPtr.baseAddress!.assumingMemoryBound(to: UInt8.self)
                )
            }
        }

        guard status == OQS_SUCCESS else {
            throw LibOQSError.operationFailed("Decapsulation failed")
        }

        return sharedSecretBuf.toData()
    }

    // MARK: - Algorithm Properties

    /// Public key size in bytes
    var publicKeyLength: Int {
        guard let kem = kem else { return 0 }
        return Int(kem.pointee.length_public_key)
    }

    /// Secret key size in bytes
    var secretKeyLength: Int {
        guard let kem = kem else { return 0 }
        return Int(kem.pointee.length_secret_key)
    }

    /// Ciphertext size in bytes
    var ciphertextLength: Int {
        guard let kem = kem else { return 0 }
        return Int(kem.pointee.length_ciphertext)
    }

    /// Shared secret size in bytes
    var sharedSecretLength: Int {
        guard let kem = kem else { return 0 }
        return Int(kem.pointee.length_shared_secret)
    }

    /// Algorithm name
    var algorithmName: String {
        guard let kem = kem, let name = kem.pointee.method_name else {
            return algorithm.rawValue
        }
        return String(cString: name)
    }

    /// NIST security level (1-5)
    var nistLevel: UInt8 {
        guard let kem = kem else { return 0 }
        return kem.pointee.claimed_nist_level
    }

    /// Whether KEM provides IND-CCA security
    var isCCA: Bool {
        guard let kem = kem else { return false }
        return kem.pointee.ind_cca
    }
}
