#!/usr/bin/env node

/**
 * Generate config from .env file for all platforms
 * This script reads .env and generates:
 * - .env.generated.json for React Native (src/config.ts)
 * - ios/GeneratedConfig.swift for iOS native modules
 * - android/app/src/main/java/com/sovereignnetworkmobile/config/GeneratedConfig.kt for Android
 *
 * This ensures .env is the SINGLE SOURCE OF TRUTH for all platforms
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const envPath = path.join(rootDir, '.env');
const generatedJsonPath = path.join(rootDir, '.env.generated.json');
const iosConfigPath = path.join(rootDir, 'ios', 'GeneratedConfig.swift');
const androidConfigPath = path.join(rootDir, 'android', 'app', 'src', 'main', 'java', 'com', 'sovereignnetworkmobile', 'config', 'GeneratedConfig.kt');

// Parse .env file
function parseEnv(filePath) {
  if (!fs.existsSync(filePath)) {
    console.warn(`Warning: ${filePath} not found, using defaults`);
    return {};
  }

  const content = fs.readFileSync(filePath, 'utf8');
  const config = {};

  content.split('\n').forEach(line => {
    line = line.trim();
    // Skip empty lines and comments
    if (!line || line.startsWith('#')) {
      return;
    }

    const [key, ...valueParts] = line.split('=');
    if (key && valueParts.length > 0) {
      config[key.trim()] = valueParts.join('=').trim();
    }
  });

  return config;
}

// Extract host and port from URL
function parseNodeUrl(url) {
  try {
    const parsed = new URL(url);
    const host = parsed.hostname;
    const port = parsed.port || 9334;
    return { host, port };
  } catch {
    // Fallback to manual parsing for simple URLs
    const match = url.match(/^https?:\/\/([^:]+):?(\d+)?/);
    if (match) {
      return { host: match[1], port: parseInt(match[2], 10) || 9334 };
    }
    return { host: 'g1.thesovereignnetwork.org', port: 9334 };
  }
}

// Parse node registry: "host:port:pin_hex,host:port:pin_hex,..."
// Returns array of { host, port, pin } objects
function parseNodeRegistry(registryStr) {
  if (!registryStr) return [];
  return registryStr.split(',').map(entry => {
    const parts = entry.trim().split(':');
    if (parts.length < 2) return null;
    // parts: [host, port, pin_hex (optional)]
    return { host: parts[0], port: parseInt(parts[1], 10), pin: parts[2] || '' };
  }).filter(Boolean);
}

// Generate config
const envConfig = parseEnv(envPath);
const nodeUrl = envConfig.ZHTP_NODE_URL || 'http://g1.thesovereignnetwork.org:9334';
const { host: nodeHost, port: nodePort } = parseNodeUrl(nodeUrl);
const sovTokenId = envConfig.SOV_TOKEN_ID || null;
const chainId = envConfig.CHAIN_ID || '2';
const nodeRegistry = parseNodeRegistry(envConfig.ZHTP_NODE_REGISTRY);
// Control plane pin = pin for the primary node host
const controlNodeEntry = nodeRegistry.find(n => n.host === nodeHost) || nodeRegistry[0];
const certificatePin = controlNodeEntry?.pin || '';

// 1. Generate JSON config for React Native
const generatedConfig = {
  ZHTP_NODE_URL: nodeUrl,
  ZHTP_NODE_HOST: nodeHost,
  ZHTP_NODE_PORT: nodePort,
  CERTIFICATE_PIN: certificatePin, // empty = system CA trust
  SOV_TOKEN_ID: sovTokenId,
  CHAIN_ID: chainId,
  NODE_REGISTRY: nodeRegistry,
};

fs.writeFileSync(
  generatedJsonPath,
  JSON.stringify(generatedConfig, null, 2),
  'utf8'
);

console.log(`✓ Generated React Native config at ${generatedJsonPath}`);
console.log(`  ZHTP_NODE_URL: ${generatedConfig.ZHTP_NODE_URL}`);
console.log(`  ZHTP_NODE_HOST: ${generatedConfig.ZHTP_NODE_HOST}`);
console.log(`  ZHTP_NODE_PORT: ${generatedConfig.ZHTP_NODE_PORT}`);
console.log(`  CERTIFICATE_PIN: ${certificatePin || '(none — system CA trust)'}`);
console.log(`  SOV_TOKEN_ID: ${sovTokenId || '(not set)'}`);
console.log(`  CHAIN_ID: ${chainId}`);

// 2. Generate iOS Swift config
const iosSpkiEntries = nodeRegistry.map(n => `        "${n.host}": "${n.pin}",`).join('\n');
const iosConfig = `import Foundation

/**
 * AUTO-GENERATED FILE - Do not edit manually
 * Generated by scripts/generate-config.js from .env file
 * Single source of truth: .env file
 */

struct GeneratedConfig {
    // Node/Server Configuration
    static let nodeUrl = "${nodeUrl}"
    static let nodeHost = "${nodeHost}"
    static let nodePort: UInt16 = ${nodePort}

    // QUIC Control Plane (used by NativeQuicModule for authenticated requests)
    static let quinnControlPlaneHost = "${nodeHost}"
    static let quinnControlPlanePort: UInt16 = ${nodePort}
    // Empty = use hostname as SNI
    static let quinnControlPlaneServerName = ""

    // SPKI pin for the control plane node (SHA-256 of SubjectPublicKeyInfo, hex-encoded)
    static let quinnSpkiPinHex = "${certificatePin}"

    // Per-host SPKI pins — generated from ZHTP_NODE_REGISTRY in .env
    private static let spkiPins: [String: String] = [
${iosSpkiEntries}
    ]

    static func spkiPin(for host: String) -> String {
        return spkiPins[host] ?? quinnSpkiPinHex
    }
}
`;

// Ensure directory exists
const iosDir = path.dirname(iosConfigPath);
if (!fs.existsSync(iosDir)) {
  fs.mkdirSync(iosDir, { recursive: true });
}

fs.writeFileSync(iosConfigPath, iosConfig, 'utf8');
console.log(`✓ Generated iOS config at ${iosConfigPath}`);

// 3. Generate Android Kotlin config
const androidSpkiEntries = nodeRegistry.map(n => `        "${n.host}" to "${n.pin}",`).join('\n');
const androidConfig = `package com.sovereignnetworkmobile.config

/**
 * AUTO-GENERATED FILE - Do not edit manually
 * Generated by scripts/generate-config.js from .env file
 * Single source of truth: .env file
 */

object GeneratedConfig {
    // Node/Server Configuration
    const val NODE_URL = "${nodeUrl}"
    const val NODE_HOST = "${nodeHost}"
    const val NODE_PORT = ${nodePort}

    // QUIC Control Plane (used by NativeQuicModule for authenticated requests)
    const val QUINN_CONTROL_PLANE_HOST = "${nodeHost}"
    const val QUINN_CONTROL_PLANE_PORT = ${nodePort}
    // Empty = use hostname as SNI
    const val QUINN_CONTROL_PLANE_SERVER_NAME = ""

    // SPKI pin for the control plane node (SHA-256 of SubjectPublicKeyInfo, hex-encoded)
    const val QUINN_SPKI_PIN_HEX = "${certificatePin}"

    // Per-host SPKI pins — generated from ZHTP_NODE_REGISTRY in .env
    private val SPKI_PINS: Map<String, String> = mapOf(
${androidSpkiEntries}
    )

    fun spkiPinFor(host: String): String = SPKI_PINS[host] ?: QUINN_SPKI_PIN_HEX
}
`;

// Ensure directory exists
const androidDir = path.dirname(androidConfigPath);
if (!fs.existsSync(androidDir)) {
  fs.mkdirSync(androidDir, { recursive: true });
}

fs.writeFileSync(androidConfigPath, androidConfig, 'utf8');
console.log(`✓ Generated Android config at ${androidConfigPath}`);

console.log(`\n✅ All platform configs generated from .env - single source of truth established!`);
