#!/usr/bin/env node

/**
 * Generate config from .env file for all platforms
 * This script reads .env and generates:
 * - .env.generated.json for React Native (src/config.ts)
 * - ios/GeneratedConfig.swift for iOS native modules
 * - android/app/src/main/java/com/sovereignnetworkmobile/config/GeneratedConfig.kt for Android
 *
 * This ensures .env is the SINGLE SOURCE OF TRUTH for all platforms
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const envPath = path.join(rootDir, '.env');
const generatedJsonPath = path.join(rootDir, '.env.generated.json');
const iosConfigPath = path.join(rootDir, 'ios', 'GeneratedConfig.swift');
const androidConfigPath = path.join(rootDir, 'android', 'app', 'src', 'main', 'java', 'com', 'sovereignnetworkmobile', 'config', 'GeneratedConfig.kt');

// Parse .env file
function parseEnv(filePath) {
  if (!fs.existsSync(filePath)) {
    console.warn(`Warning: ${filePath} not found, using defaults`);
    return {};
  }

  const content = fs.readFileSync(filePath, 'utf8');
  const config = {};

  content.split('\n').forEach(line => {
    line = line.trim();
    // Skip empty lines and comments
    if (!line || line.startsWith('#')) {
      return;
    }

    const [key, ...valueParts] = line.split('=');
    if (key && valueParts.length > 0) {
      config[key.trim()] = valueParts.join('=').trim();
    }
  });

  return config;
}

// Extract host and port from URL
function parseNodeUrl(url) {
  try {
    const parsed = new URL(url);
    const host = parsed.hostname;
    const port = parsed.port || 9334;
    return { host, port };
  } catch {
    // Fallback to manual parsing for simple URLs
    const match = url.match(/^https?:\/\/([^:]+):?(\d+)?/);
    if (match) {
      return { host: match[1], port: parseInt(match[2], 10) || 9334 };
    }
    return { host: '77.42.37.161', port: 9334 };
  }
}

// Generate config
const envConfig = parseEnv(envPath);
const nodeUrl = envConfig.ZHTP_NODE_URL || 'http://77.42.37.161:9334';
const { host: nodeHost, port: nodePort } = parseNodeUrl(nodeUrl);
const certificatePin = envConfig.CERTIFICATE_PIN || 'd21aa1f13cea799f96588a274c210c6de46786f098dc321477d8e04b7d87e058'; // Default testnet pin

// 1. Generate JSON config for React Native
const generatedConfig = {
  ZHTP_NODE_URL: nodeUrl,
  ZHTP_NODE_HOST: nodeHost,
  ZHTP_NODE_PORT: nodePort,
  CERTIFICATE_PIN: certificatePin,
};

fs.writeFileSync(
  generatedJsonPath,
  JSON.stringify(generatedConfig, null, 2),
  'utf8'
);

console.log(`✓ Generated React Native config at ${generatedJsonPath}`);
console.log(`  ZHTP_NODE_URL: ${generatedConfig.ZHTP_NODE_URL}`);
console.log(`  ZHTP_NODE_HOST: ${generatedConfig.ZHTP_NODE_HOST}`);
console.log(`  ZHTP_NODE_PORT: ${generatedConfig.ZHTP_NODE_PORT}`);
console.log(`  CERTIFICATE_PIN: ${certificatePin}`);

// 2. Generate iOS Swift config
const iosConfig = `import Foundation

/**
 * AUTO-GENERATED FILE - Do not edit manually
 * Generated by scripts/generate-config.js from .env file
 * Single source of truth: .env file
 */

struct GeneratedConfig {
    // Node/Server Configuration
    static let nodeUrl = "${nodeUrl}"
    static let nodeHost = "${nodeHost}"
    static let nodePort: UInt16 = ${nodePort}

    // QUIC Control Plane (used by NativeQuicModule for authenticated requests)
    static let quinnControlPlaneHost = "${nodeHost}"
    static let quinnControlPlanePort: UInt16 = ${nodePort}
    static let quinnControlPlaneServerName = "zhtp-mesh"

    // SPKI Pin (this should match your server certificate)
    // This is used for certificate pinning in QUIC connections
    static let quinnSpkiPinHex = "${certificatePin}"
}
`;

// Ensure directory exists
const iosDir = path.dirname(iosConfigPath);
if (!fs.existsSync(iosDir)) {
  fs.mkdirSync(iosDir, { recursive: true });
}

fs.writeFileSync(iosConfigPath, iosConfig, 'utf8');
console.log(`✓ Generated iOS config at ${iosConfigPath}`);

// 3. Generate Android Kotlin config
const androidConfig = `package com.sovereignnetworkmobile.config

/**
 * AUTO-GENERATED FILE - Do not edit manually
 * Generated by scripts/generate-config.js from .env file
 * Single source of truth: .env file
 */

object GeneratedConfig {
    // Node/Server Configuration
    const val NODE_URL = "${nodeUrl}"
    const val NODE_HOST = "${nodeHost}"
    const val NODE_PORT = ${nodePort}

    // QUIC Control Plane (used by NativeQuicModule for authenticated requests)
    const val QUINN_CONTROL_PLANE_HOST = "${nodeHost}"
    const val QUINN_CONTROL_PLANE_PORT = ${nodePort}
    const val QUINN_CONTROL_PLANE_SERVER_NAME = "zhtp-mesh"

    // SPKI Pin (this should match your server certificate)
    // This is used for certificate pinning in QUIC connections
    const val QUINN_SPKI_PIN_HEX = "${certificatePin}"
}
`;

// Ensure directory exists
const androidDir = path.dirname(androidConfigPath);
if (!fs.existsSync(androidDir)) {
  fs.mkdirSync(androidDir, { recursive: true });
}

fs.writeFileSync(androidConfigPath, androidConfig, 'utf8');
console.log(`✓ Generated Android config at ${androidConfigPath}`);

console.log(`\n✅ All platform configs generated from .env - single source of truth established!`);
