/**
 * Application Configuration
 * Single source of truth for all URLs, endpoints, and network settings
 * NOTE: Node URL MUST be set in .env file - change nowhere else
 *
 * The .env file is read by a build script (scripts/generate-config.js) that
 * sets these values. This ensures:
 * 1. Single source of truth in .env
 * 2. No hardcoded IPs in multiple files
 * 3. Clean build-time configuration injection
 */

// =============================================================================
// NETWORK CONFIGURATION
// =============================================================================

/**
 * Default SOV Node URL
 * Set in .env file: ZHTP_NODE_URL=http://your-node-ip:9334
 * The development node only supports pure QUIC/UDP - no HTTP fallback
 * Port 9334 is the standard SOV port
 *
 * ⚠️  SINGLE POINT TO CHANGE NODE URL:
 *     Edit .env file only:
 *     - Local testing:  ZHTP_NODE_URL=http://192.168.1.30:9334
 *     - Remote server:  ZHTP_NODE_URL=http://77.42.37.161:9334
 *
 * This value is injected at build time via scripts/generate-config.js
 */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const generatedConfig = require('../.env.generated.json');

// Values are generated by scripts/generate-config.js at build time from .env
// REQUIRED: .env.generated.json must exist - run "npm run generate-config" first
if (!generatedConfig.ZHTP_NODE_URL) {
  throw new Error(
    'CRITICAL: .env.generated.json not found or missing ZHTP_NODE_URL.\n' +
    'Run "npm run generate-config" to generate configuration from .env file.'
  );
}

export const DEFAULT_SOV_NODE_URL = generatedConfig.ZHTP_NODE_URL;
export const CERTIFICATE_PIN = generatedConfig.CERTIFICATE_PIN;
export const SOV_TOKEN_ID: string | null = generatedConfig.SOV_TOKEN_ID ?? null;
export const CHAIN_ID: number = Number.isFinite(Number(generatedConfig.CHAIN_ID))
  ? Number(generatedConfig.CHAIN_ID)
  : 2;

/**
 * Default node host and port (pre-parsed from URL by build script)
 * These are generated by scripts/generate-config.js at build time from .env
 */
export const DEFAULT_NODE_HOST = generatedConfig.ZHTP_NODE_HOST;
export const DEFAULT_NODE_PORT = parseInt(String(generatedConfig.ZHTP_NODE_PORT), 10);

/**
 * Network type - testnet or mainnet
 */
export const DEFAULT_NETWORK_TYPE: 'testnet' | 'mainnet' = 'testnet';

/**
 * Determine if testnet uses self-signed certificates
 * Testnet (77.42.37.161) uses self-signed rcgen certificates with certificate pinning
 * Mainnet would use proper SSL certificates
 */
function isTestnetWithSelfSignedCerts(): boolean {
  const networkType = DEFAULT_NETWORK_TYPE;
  return networkType === 'testnet'; // Testnet server uses self-signed cert
}

// =============================================================================
// API ENDPOINTS
// =============================================================================

/**
 * All API endpoint paths - matches the sovereign-net-api-client library
 * These are relative paths appended to the node URL
 */
export const API_ENDPOINTS = {
  // Identity endpoints
  identity: {
    create: '/api/v1/identity/create',
    login: '/api/v1/identity/login',
    signin: '/api/v1/identity/signin',
    verify: '/api/v1/identity/verify',
    exists: '/api/v1/identity/exists',
  },

  // Wallet endpoints
  wallet: {
    list: '/api/v1/wallet/list', // /{identity_id}
    balance: '/api/v1/wallet/balance', // /{type}/{identity_id}
    send: '/api/v1/wallet/send',
    receive: '/api/v1/wallet/receive',
    stake: '/api/v1/wallet/stake',
    unstake: '/api/v1/wallet/unstake',
    transactions: '/api/v1/wallet/transactions', // /{wallet_id}
  },

  // DAO endpoints
  dao: {
    proposals: {
      list: '/api/v1/dao/proposals/list',
      get: '/api/v1/dao/proposals', // /{proposal_id}
      create: '/api/v1/dao/proposals/create',
    },
    vote: {
      cast: '/api/v1/dao/vote/cast',
      history: '/api/v1/dao/vote/history', // /{identity_id}
    },
  },

  // UBI endpoints
  ubi: {
    claim: '/api/v1/ubi/claim',
  },

  // Network/Protocol endpoints
  network: {
    health: '/api/v1/protocol/health',
    peers: '/api/v1/blockchain/network/peers',
    status: '/api/v1/blockchain/network/status',
  },

  // Recovery endpoints
  recovery: {
    seed: '/api/v1/identity/recovery/seed',
    backup: '/api/v1/identity/recovery/backup',
    guardians: {
      list: '/api/v1/identity/guardians/list',
      add: '/api/v1/identity/guardians/add',
      remove: '/api/v1/identity/guardians/remove',
      initiate: '/api/v1/identity/recovery/guardians/initiate',
      approve: '/api/v1/identity/recovery/guardians/approve',
      status: '/api/v1/identity/recovery/guardians/status',
    },
  },

  // ZK-DID endpoints
  zkdid: {
    create: '/api/v1/zkdid/create',
    verify: '/api/v1/zkdid/verify',
    prove: '/api/v1/zkdid/prove',
  },
} as const;

// =============================================================================
// QUIC/TRANSPORT CONFIGURATION
// =============================================================================

/**
 * QUIC transport settings
 */
export const QUIC_CONFIG = {
  /** ALPN protocol identifier for SOV */
  alpnProtocol: 'zhtp/1.0',

  /** Default request timeout in seconds */
  defaultTimeout: 30,

  /** Accept self-signed certificates in:
   * 1. Development builds (__DEV__)
   * 2. Testnet (uses self-signed rcgen certificates with certificate pinning)
   * Mainnet would require proper SSL certificates
   */
  insecure: __DEV__ || isTestnetWithSelfSignedCerts(),

  /** Maximum response size in bytes (1MB) */
  maxResponseSize: 1024 * 1024,

  /** Idle timeout in seconds */
  idleTimeout: 30,
} as const;

// =============================================================================
// APP DEFAULTS
// =============================================================================

/**
 * Default app configuration values
 */
export const APP_DEFAULTS = {
  /** Use mock data service in development */
  useMockData: false,

  /** Enable biometric authentication if available */
  enableBiometrics: true,

  /** Debug mode - extra logging */
  debugMode: __DEV__,
} as const;

// =============================================================================
// FEATURE FLAGS
// =============================================================================

/**
 * Compile-time feature flags for experimental or development features
 * Set flags based on development mode - only visible in dev builds by default
 */
export const FEATURE_FLAGS = {
  /** Enable Token Creator UI - create, mint, transfer tokens */
  ENABLE_TOKEN_CREATOR: __DEV__,
} as const;

// =============================================================================
// LEGACY EXPORTS (for backward compatibility)
// =============================================================================

/**
 * Legacy export for backward compatibility during migration
 */
export const DEFAULT_ZHTP_NODE_URL = DEFAULT_SOV_NODE_URL;
export const SOV_NODE_URL = DEFAULT_SOV_NODE_URL;
export const ZHTP_NODE_URL = DEFAULT_SOV_NODE_URL;

/**
 * Legacy config object - use individual exports above for new code
 */
export const config = {
  DEFAULT_ZHTP_NODE_URL: DEFAULT_SOV_NODE_URL,
  SOV_NODE_URL: DEFAULT_SOV_NODE_URL,
  ZHTP_NODE_URL: DEFAULT_SOV_NODE_URL,
  NODE_HOST: DEFAULT_NODE_HOST,
  NODE_PORT: DEFAULT_NODE_PORT,
  CERTIFICATE_PIN,
  SOV_TOKEN_ID,
  CHAIN_ID,
  NETWORK_TYPE: DEFAULT_NETWORK_TYPE,
  API_ENDPOINTS,
  QUIC_CONFIG,
  APP_DEFAULTS,
};

export default config;
